/**
 * Canonical Permission Keys & Scopes from RTS Help Desk BRD v14 (Section 3.5 & 16.27).
 * All access control in the application evaluates against these permissions.
 */

export const PERMISSIONS = {
  // ─── User Management (Admin GLOBAL) ───
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_VIEW: "USER_VIEW",
  USER_PERFORMANCE_VIEW: "USER_PERFORMANCE_VIEW",

  // ─── Master Data Management ───
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_DELETE: "DEPARTMENT_DELETE",
  DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
  TEAM_CREATE: "TEAM_CREATE",
  TEAM_UPDATE: "TEAM_UPDATE",
  TEAM_DEPARTMENT_CHANGE: "TEAM_DEPARTMENT_CHANGE",
  TEAM_DELETE: "TEAM_DELETE",
  TEAM_VIEW: "TEAM_VIEW",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_VIEW: "PROJECT_VIEW",
  PRIORITY_MANAGE: "PRIORITY_MANAGE",
  PRIORITY_CREATE: "PRIORITY_CREATE",
  PRIORITY_UPDATE: "PRIORITY_UPDATE",
  PRIORITY_RETIRE: "PRIORITY_RETIRE",
  STATUS_CREATE: "STATUS_CREATE",
  STATUS_UPDATE: "STATUS_UPDATE",
  STATUS_RETIRE: "STATUS_RETIRE",
  TICKET_FIELD_MANAGE: "TICKET_FIELD_MANAGE",
  ROLE_MANAGE: "ROLE_MANAGE",
  TEAM_MEMBERSHIP_MANAGE: "TEAM_MEMBERSHIP_MANAGE",

  // ─── Ticket Operations ───
  TICKET_CREATE: "TICKET_CREATE",
  TICKET_VIEW: "TICKET_VIEW",
  TICKET_UPDATE: "TICKET_UPDATE",
  TICKET_ASSIGN: "TICKET_ASSIGN",
  TICKET_REASSIGN: "TICKET_REASSIGN",
  TICKET_CHANGE_STATUS: "TICKET_CHANGE_STATUS",
  TICKET_CHANGE_PRIORITY: "TICKET_CHANGE_PRIORITY",
  TICKET_CLOSE: "TICKET_CLOSE",
  TICKET_CREATE_SUBTICKET: "TICKET_CREATE_SUBTICKET",
  TICKET_ADD_REMARK: "TICKET_ADD_REMARK",
  TICKET_ATTACHMENT_MANAGE: "TICKET_ATTACHMENT_MANAGE",
  TICKET_LOG_TIME: "TICKET_LOG_TIME",
  TICKET_HISTORY_VIEW: "TICKET_HISTORY_VIEW",
  TICKET_TEAM_MANAGE: "TICKET_TEAM_MANAGE",

  // ─── Dashboards & Reporting ───
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // ─── System Administration ───
  SYSTEM_SETTINGS_MANAGE: "SYSTEM_SETTINGS_MANAGE",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type PermissionScope =
  | "GLOBAL"
  | "OWN"
  | "ASSIGNED"
  | "TEAM"
  | "DEPARTMENT";

export const PERMISSION_ALLOWED_SCOPES: Record<string, PermissionScope[]> = {
  // Scoped permissions
  DEPARTMENT_VIEW: ["GLOBAL", "OWN"],
  TEAM_VIEW: ["GLOBAL", "TEAM"],
  PROJECT_VIEW: ["GLOBAL", "TEAM"],
  STATUS_CREATE: ["GLOBAL", "TEAM"],
  TICKET_CREATE: ["GLOBAL", "TEAM"],
  TICKET_VIEW: ["GLOBAL", "TEAM", "OWN"],
  TICKET_UPDATE: ["GLOBAL", "OWN", "ASSIGNED"],
  TICKET_ASSIGN: ["GLOBAL", "OWN"],
  TICKET_REASSIGN: ["GLOBAL", "OWN"],
  TICKET_CHANGE_STATUS: ["GLOBAL", "ASSIGNED"],
  TICKET_CHANGE_PRIORITY: ["GLOBAL", "OWN", "ASSIGNED"],
  TICKET_CREATE_SUBTICKET: ["GLOBAL", "OWN"],
  TICKET_CLOSE: ["GLOBAL", "ASSIGNED"],
  TICKET_ADD_REMARK: ["GLOBAL", "OWN"],
  TICKET_ATTACHMENT_MANAGE: ["GLOBAL", "OWN"],
  TICKET_LOG_TIME: ["GLOBAL", "OWN"],
  TICKET_HISTORY_VIEW: ["GLOBAL", "TEAM", "OWN"],
  DASHBOARD_VIEW: ["GLOBAL", "OWN"],

  // Global-only permissions
  USER_VIEW: ["GLOBAL"],
  USER_UPDATE: ["GLOBAL"],
  USER_PERFORMANCE_VIEW: ["GLOBAL"],
  USER_CREATE: ["GLOBAL"],
  USER_DELETE: ["GLOBAL"],
  DEPARTMENT_CREATE: ["GLOBAL"],
  DEPARTMENT_UPDATE: ["GLOBAL"],
  DEPARTMENT_DELETE: ["GLOBAL"],
  TEAM_CREATE: ["GLOBAL"],
  TEAM_UPDATE: ["GLOBAL"],
  TEAM_DEPARTMENT_CHANGE: ["GLOBAL"],
  TEAM_DELETE: ["GLOBAL"],
  PROJECT_CREATE: ["GLOBAL"],
  PROJECT_UPDATE: ["GLOBAL"],
  PROJECT_DELETE: ["GLOBAL"],
  PRIORITY_MANAGE: ["GLOBAL"],
  PRIORITY_CREATE: ["GLOBAL"],
  PRIORITY_UPDATE: ["GLOBAL"],
  PRIORITY_RETIRE: ["GLOBAL"],
  STATUS_UPDATE: ["GLOBAL"],
  STATUS_RETIRE: ["GLOBAL"],
  TICKET_FIELD_MANAGE: ["GLOBAL"],
  TEAM_MEMBERSHIP_MANAGE: ["GLOBAL"],
  TICKET_TEAM_MANAGE: ["GLOBAL"],
  ROLE_MANAGE: ["GLOBAL"],
  SYSTEM_SETTINGS_MANAGE: ["GLOBAL"],
};
